export const DEFAULT_USER_ID = 15

export const ROLE_LABELS = {
  VICE_LEADER: '부장',
  TEACHER_ADMIN: '교사 총무',
  TEACHER: '교사',
  STUDENT: '학생',
}

export const seedUsers = [
  { userId: 3, name: '박종현', classId: null, className: null, role: 'VICE_LEADER' },
  { userId: 4, name: '최용관', classId: null, className: null, role: 'TEACHER_ADMIN' },
  { userId: 5, name: '김민재', classId: 1, className: '중등1반', role: 'TEACHER' },
  { userId: 6, name: '김태형', classId: 2, className: '중등2반', role: 'TEACHER' },
  { userId: 7, name: '이도은', classId: 3, className: '중등3반', role: 'TEACHER' },
  { userId: 8, name: '오한나', classId: 4, className: '중등4반', role: 'TEACHER' },
  { userId: 9, name: '박민욱', classId: 5, className: '고등1반', role: 'TEACHER' },
  { userId: 10, name: '류상현', classId: 6, className: '고등2반', role: 'TEACHER' },
  { userId: 11, name: '전도원', classId: 7, className: '고등3반', role: 'TEACHER' },
  { userId: 12, name: '유정아', classId: 8, className: '고등4반', role: 'TEACHER' },
  { userId: 13, name: '정성훈', classId: 9, className: '고등5반', role: 'TEACHER' },
  { userId: 14, name: '박초은', classId: 10, className: '고등6반', role: 'TEACHER' },
  { userId: 15, name: '김이룬', classId: 1, className: '중등1반', role: 'STUDENT' },
  { userId: 16, name: '김주혁', classId: 1, className: '중등1반', role: 'STUDENT' },
  { userId: 17, name: '주재윤', classId: 1, className: '중등1반', role: 'STUDENT' },
  { userId: 18, name: '문예준', classId: 1, className: '중등1반', role: 'STUDENT' },
  { userId: 19, name: '김이레', classId: 1, className: '중등1반', role: 'STUDENT' },
  { userId: 20, name: '김율', classId: 2, className: '중등2반', role: 'STUDENT' },
  { userId: 21, name: '황우빈', classId: 2, className: '중등2반', role: 'STUDENT' },
  { userId: 22, name: '노대윤', classId: 2, className: '중등2반', role: 'STUDENT' },
  { userId: 23, name: '서연우', classId: 2, className: '중등2반', role: 'STUDENT' },
  { userId: 24, name: '나하경', classId: 3, className: '중등3반', role: 'STUDENT' },
  { userId: 25, name: '전지효', classId: 3, className: '중등3반', role: 'STUDENT' },
  { userId: 26, name: '손채림', classId: 3, className: '중등3반', role: 'STUDENT' },
  { userId: 27, name: '전가람', classId: 3, className: '중등3반', role: 'STUDENT' },
  { userId: 28, name: '김소은', classId: 4, className: '중등4반', role: 'STUDENT' },
  { userId: 29, name: '정예빈', classId: 4, className: '중등4반', role: 'STUDENT' },
  { userId: 30, name: '정은', classId: 4, className: '중등4반', role: 'STUDENT' },
  { userId: 31, name: '박혜은', classId: 4, className: '중등4반', role: 'STUDENT' },
  { userId: 32, name: '김서준', classId: 5, className: '고등1반', role: 'STUDENT' },
  { userId: 33, name: '최강민', classId: 5, className: '고등1반', role: 'STUDENT' },
  { userId: 34, name: '김병섭', classId: 5, className: '고등1반', role: 'STUDENT' },
  { userId: 35, name: '손태규', classId: 5, className: '고등1반', role: 'STUDENT' },
  { userId: 36, name: '서지우', classId: 5, className: '고등1반', role: 'STUDENT' },
  { userId: 37, name: '김성준', classId: 6, className: '고등2반', role: 'STUDENT' },
  { userId: 38, name: '나하람', classId: 6, className: '고등2반', role: 'STUDENT' },
  { userId: 39, name: '박지호', classId: 6, className: '고등2반', role: 'STUDENT' },
  { userId: 40, name: '박현서', classId: 6, className: '고등2반', role: 'STUDENT' },
  { userId: 41, name: '성지석', classId: 6, className: '고등2반', role: 'STUDENT' },
  { userId: 42, name: '김가연', classId: 7, className: '고등3반', role: 'STUDENT' },
  { userId: 43, name: '김다연', classId: 7, className: '고등3반', role: 'STUDENT' },
  { userId: 44, name: '김도연', classId: 7, className: '고등3반', role: 'STUDENT' },
  { userId: 45, name: '김주아', classId: 7, className: '고등3반', role: 'STUDENT' },
  { userId: 46, name: '박은솔', classId: 7, className: '고등3반', role: 'STUDENT' },
  { userId: 47, name: '서은민', classId: 7, className: '고등3반', role: 'STUDENT' },
  { userId: 48, name: '박서연', classId: 8, className: '고등4반', role: 'STUDENT' },
  { userId: 49, name: '윤예린', classId: 8, className: '고등4반', role: 'STUDENT' },
  { userId: 50, name: '김건', classId: 9, className: '고등5반', role: 'STUDENT' },
  { userId: 51, name: '김두현', classId: 9, className: '고등5반', role: 'STUDENT' },
  { userId: 52, name: '박은수', classId: 9, className: '고등5반', role: 'STUDENT' },
  { userId: 53, name: '박정호', classId: 9, className: '고등5반', role: 'STUDENT' },
  { userId: 54, name: '오승혁', classId: 9, className: '고등5반', role: 'STUDENT' },
  { userId: 55, name: '전하람', classId: 9, className: '고등5반', role: 'STUDENT' },
  { userId: 56, name: '정해인', classId: 9, className: '고등5반', role: 'STUDENT' },
  { userId: 57, name: '황재혁', classId: 9, className: '고등5반', role: 'STUDENT' },
  { userId: 58, name: '김희영', classId: 10, className: '고등6반', role: 'STUDENT' },
  { userId: 59, name: '문은혜', classId: 10, className: '고등6반', role: 'STUDENT' },
  { userId: 60, name: '주서윤', classId: 10, className: '고등6반', role: 'STUDENT' },
  { userId: 61, name: '최서아', classId: 10, className: '고등6반', role: 'STUDENT' },
]

export const seedClasses = [
  { classId: 1, className: '중등1반', score: 0, teacherCount: 1, studentCount: 5, totalCount: 6 },
  { classId: 2, className: '중등2반', score: 0, teacherCount: 1, studentCount: 4, totalCount: 5 },
  { classId: 3, className: '중등3반', score: 0, teacherCount: 1, studentCount: 4, totalCount: 5 },
  { classId: 4, className: '중등4반', score: 0, teacherCount: 1, studentCount: 4, totalCount: 5 },
  { classId: 5, className: '고등1반', score: 0, teacherCount: 1, studentCount: 5, totalCount: 6 },
  { classId: 6, className: '고등2반', score: 0, teacherCount: 1, studentCount: 5, totalCount: 6 },
  { classId: 7, className: '고등3반', score: 0, teacherCount: 1, studentCount: 6, totalCount: 7 },
  { classId: 8, className: '고등4반', score: 0, teacherCount: 1, studentCount: 2, totalCount: 3 },
  { classId: 9, className: '고등5반', score: 0, teacherCount: 1, studentCount: 8, totalCount: 9 },
  { classId: 10, className: '고등6반', score: 0, teacherCount: 1, studentCount: 4, totalCount: 5 },
]
